from setuptools import setup, find_packages

setup(
    name="diffusion_policy",
    version="0.1.0",
    description="Diffusion Policy from Scratch.",
    author="MoriBot",
    author_email="mrahme97@gmail.com",
    url="https://github.com/moribots/2d-arm-diffusion",
    packages=find_packages(),
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
    python_requires=">=3.8",
    install_requires=[
        "torch>=2.0.0",
        "torchvision>=0.10.0",
        "einops>=0.6.0",
        "pyarrow>=10.0.0",
        "pygame>=2.1",
        "gymnasium>=0.28.1",
        "gym-pusht>=0.0.1",
        "datasets>=2.0.0",
        "pillow>=9.0.0",
        "numpy>=1.20.0",
        "wandb>=0.15.0",
        "tqdm>=4.62.0",
        "opencv-python>=4.5.0",
        "tabulate>=0.8.9",
        "pandas>=1.3.0",
        "matplotlib>=3.4.0",
        "pytorch_lightning>=2.0.0",
        "imageio>=2.25.0",
    ],
)
